/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdicionarRouteImport } from './routes/_authenticated/adicionar'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedComunidadeRouteImport } from './routes/_authenticated/comunidade'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDesempenhoRouteImport } from './routes/_authenticated/desempenho'
import { Route as AuthenticatedErrosRouteImport } from './routes/_authenticated/erros'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedFlashcardsRouteImport } from './routes/_authenticated/flashcards'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedLivroRouteImport } from './routes/_authenticated/livro'
import { Route as AuthenticatedMapasRouteImport } from './routes/_authenticated/mapas'
import { Route as AuthenticatedPlanoRouteImport } from './routes/_authenticated/plano'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as AuthenticatedRevisoesRouteImport } from './routes/_authenticated/revisoes'
import { Route as AuthenticatedRitmoRouteImport } from './routes/_authenticated/ritmo'
import { Route as AuthenticatedSimuladosRouteImport } from './routes/_authenticated/simulados'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedLivroBookIdRouteImport } from './routes/_authenticated/livro.$bookId'
import { Route as AuthenticatedMaterialMaterialIdRouteImport } from './routes/_authenticated/material.$materialId'
import { Route as ApiPublicNotifyCronRouteImport } from './routes/api/public/notify-cron'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdicionarRoute = AuthenticatedAdicionarRouteImport.update({
  id: '/adicionar',
  path: '/adicionar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComunidadeRoute = AuthenticatedComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesempenhoRoute = AuthenticatedDesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrosRoute = AuthenticatedErrosRouteImport.update({
  id: '/erros',
  path: '/erros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlashcardsRoute = AuthenticatedFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivroRoute = AuthenticatedLivroRouteImport.update({
  id: '/livro',
  path: '/livro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapasRoute = AuthenticatedMapasRouteImport.update({
  id: '/mapas',
  path: '/mapas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanoRoute = AuthenticatedPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisoesRoute = AuthenticatedRevisoesRouteImport.update({
  id: '/revisoes',
  path: '/revisoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRitmoRoute = AuthenticatedRitmoRouteImport.update({
  id: '/ritmo',
  path: '/ritmo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimuladosRoute = AuthenticatedSimuladosRouteImport.update({
  id: '/simulados',
  path: '/simulados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivroBookIdRoute =
  AuthenticatedLivroBookIdRouteImport.update({
    id: '/$bookId',
    path: '/$bookId',
    getParentRoute: () => AuthenticatedLivroRoute,
  } as any)
const AuthenticatedMaterialMaterialIdRoute =
  AuthenticatedMaterialMaterialIdRouteImport.update({
    id: '/material/$materialId',
    path: '/material/$materialId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicNotifyCronRoute = ApiPublicNotifyCronRouteImport.update({
  id: '/api/public/notify-cron',
  path: '/api/public/notify-cron',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/adicionar': typeof AuthenticatedAdicionarRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/comunidade': typeof AuthenticatedComunidadeRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/desempenho': typeof AuthenticatedDesempenhoRoute
  '/erros': typeof AuthenticatedErrosRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/livro': typeof AuthenticatedLivroRouteWithChildren
  '/mapas': typeof AuthenticatedMapasRoute
  '/plano': typeof AuthenticatedPlanoRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/revisoes': typeof AuthenticatedRevisoesRoute
  '/ritmo': typeof AuthenticatedRitmoRoute
  '/simulados': typeof AuthenticatedSimuladosRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/livro/$bookId': typeof AuthenticatedLivroBookIdRoute
  '/material/$materialId': typeof AuthenticatedMaterialMaterialIdRoute
  '/api/public/notify-cron': typeof ApiPublicNotifyCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/adicionar': typeof AuthenticatedAdicionarRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/comunidade': typeof AuthenticatedComunidadeRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/desempenho': typeof AuthenticatedDesempenhoRoute
  '/erros': typeof AuthenticatedErrosRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/livro': typeof AuthenticatedLivroRouteWithChildren
  '/mapas': typeof AuthenticatedMapasRoute
  '/plano': typeof AuthenticatedPlanoRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/revisoes': typeof AuthenticatedRevisoesRoute
  '/ritmo': typeof AuthenticatedRitmoRoute
  '/simulados': typeof AuthenticatedSimuladosRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/livro/$bookId': typeof AuthenticatedLivroBookIdRoute
  '/material/$materialId': typeof AuthenticatedMaterialMaterialIdRoute
  '/api/public/notify-cron': typeof ApiPublicNotifyCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/adicionar': typeof AuthenticatedAdicionarRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/comunidade': typeof AuthenticatedComunidadeRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/desempenho': typeof AuthenticatedDesempenhoRoute
  '/_authenticated/erros': typeof AuthenticatedErrosRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/flashcards': typeof AuthenticatedFlashcardsRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/livro': typeof AuthenticatedLivroRouteWithChildren
  '/_authenticated/mapas': typeof AuthenticatedMapasRoute
  '/_authenticated/plano': typeof AuthenticatedPlanoRoute
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/_authenticated/revisoes': typeof AuthenticatedRevisoesRoute
  '/_authenticated/ritmo': typeof AuthenticatedRitmoRoute
  '/_authenticated/simulados': typeof AuthenticatedSimuladosRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRoute
  '/_authenticated/livro/$bookId': typeof AuthenticatedLivroBookIdRoute
  '/_authenticated/material/$materialId': typeof AuthenticatedMaterialMaterialIdRoute
  '/api/public/notify-cron': typeof ApiPublicNotifyCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/adicionar'
    | '/biblioteca'
    | '/comunidade'
    | '/configuracoes'
    | '/desempenho'
    | '/erros'
    | '/favoritos'
    | '/flashcards'
    | '/inicio'
    | '/livro'
    | '/mapas'
    | '/plano'
    | '/quiz'
    | '/revisoes'
    | '/ritmo'
    | '/simulados'
    | '/tutor'
    | '/livro/$bookId'
    | '/material/$materialId'
    | '/api/public/notify-cron'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/adicionar'
    | '/biblioteca'
    | '/comunidade'
    | '/configuracoes'
    | '/desempenho'
    | '/erros'
    | '/favoritos'
    | '/flashcards'
    | '/inicio'
    | '/livro'
    | '/mapas'
    | '/plano'
    | '/quiz'
    | '/revisoes'
    | '/ritmo'
    | '/simulados'
    | '/tutor'
    | '/livro/$bookId'
    | '/material/$materialId'
    | '/api/public/notify-cron'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/adicionar'
    | '/_authenticated/biblioteca'
    | '/_authenticated/comunidade'
    | '/_authenticated/configuracoes'
    | '/_authenticated/desempenho'
    | '/_authenticated/erros'
    | '/_authenticated/favoritos'
    | '/_authenticated/flashcards'
    | '/_authenticated/inicio'
    | '/_authenticated/livro'
    | '/_authenticated/mapas'
    | '/_authenticated/plano'
    | '/_authenticated/quiz'
    | '/_authenticated/revisoes'
    | '/_authenticated/ritmo'
    | '/_authenticated/simulados'
    | '/_authenticated/tutor'
    | '/_authenticated/livro/$bookId'
    | '/_authenticated/material/$materialId'
    | '/api/public/notify-cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicNotifyCronRoute: typeof ApiPublicNotifyCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/adicionar': {
      id: '/_authenticated/adicionar'
      path: '/adicionar'
      fullPath: '/adicionar'
      preLoaderRoute: typeof AuthenticatedAdicionarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunidade': {
      id: '/_authenticated/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof AuthenticatedComunidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desempenho': {
      id: '/_authenticated/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof AuthenticatedDesempenhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/erros': {
      id: '/_authenticated/erros'
      path: '/erros'
      fullPath: '/erros'
      preLoaderRoute: typeof AuthenticatedErrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flashcards': {
      id: '/_authenticated/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livro': {
      id: '/_authenticated/livro'
      path: '/livro'
      fullPath: '/livro'
      preLoaderRoute: typeof AuthenticatedLivroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapas': {
      id: '/_authenticated/mapas'
      path: '/mapas'
      fullPath: '/mapas'
      preLoaderRoute: typeof AuthenticatedMapasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plano': {
      id: '/_authenticated/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof AuthenticatedPlanoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisoes': {
      id: '/_authenticated/revisoes'
      path: '/revisoes'
      fullPath: '/revisoes'
      preLoaderRoute: typeof AuthenticatedRevisoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ritmo': {
      id: '/_authenticated/ritmo'
      path: '/ritmo'
      fullPath: '/ritmo'
      preLoaderRoute: typeof AuthenticatedRitmoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulados': {
      id: '/_authenticated/simulados'
      path: '/simulados'
      fullPath: '/simulados'
      preLoaderRoute: typeof AuthenticatedSimuladosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livro/$bookId': {
      id: '/_authenticated/livro/$bookId'
      path: '/$bookId'
      fullPath: '/livro/$bookId'
      preLoaderRoute: typeof AuthenticatedLivroBookIdRouteImport
      parentRoute: typeof AuthenticatedLivroRoute
    }
    '/_authenticated/material/$materialId': {
      id: '/_authenticated/material/$materialId'
      path: '/material/$materialId'
      fullPath: '/material/$materialId'
      preLoaderRoute: typeof AuthenticatedMaterialMaterialIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/notify-cron': {
      id: '/api/public/notify-cron'
      path: '/api/public/notify-cron'
      fullPath: '/api/public/notify-cron'
      preLoaderRoute: typeof ApiPublicNotifyCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedLivroRouteChildren {
  AuthenticatedLivroBookIdRoute: typeof AuthenticatedLivroBookIdRoute
}

const AuthenticatedLivroRouteChildren: AuthenticatedLivroRouteChildren = {
  AuthenticatedLivroBookIdRoute: AuthenticatedLivroBookIdRoute,
}

const AuthenticatedLivroRouteWithChildren =
  AuthenticatedLivroRoute._addFileChildren(AuthenticatedLivroRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdicionarRoute: typeof AuthenticatedAdicionarRoute
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedComunidadeRoute: typeof AuthenticatedComunidadeRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDesempenhoRoute: typeof AuthenticatedDesempenhoRoute
  AuthenticatedErrosRoute: typeof AuthenticatedErrosRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedFlashcardsRoute: typeof AuthenticatedFlashcardsRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedLivroRoute: typeof AuthenticatedLivroRouteWithChildren
  AuthenticatedMapasRoute: typeof AuthenticatedMapasRoute
  AuthenticatedPlanoRoute: typeof AuthenticatedPlanoRoute
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
  AuthenticatedRevisoesRoute: typeof AuthenticatedRevisoesRoute
  AuthenticatedRitmoRoute: typeof AuthenticatedRitmoRoute
  AuthenticatedSimuladosRoute: typeof AuthenticatedSimuladosRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRoute
  AuthenticatedMaterialMaterialIdRoute: typeof AuthenticatedMaterialMaterialIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdicionarRoute: AuthenticatedAdicionarRoute,
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedComunidadeRoute: AuthenticatedComunidadeRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDesempenhoRoute: AuthenticatedDesempenhoRoute,
  AuthenticatedErrosRoute: AuthenticatedErrosRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedFlashcardsRoute: AuthenticatedFlashcardsRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedLivroRoute: AuthenticatedLivroRouteWithChildren,
  AuthenticatedMapasRoute: AuthenticatedMapasRoute,
  AuthenticatedPlanoRoute: AuthenticatedPlanoRoute,
  AuthenticatedQuizRoute: AuthenticatedQuizRoute,
  AuthenticatedRevisoesRoute: AuthenticatedRevisoesRoute,
  AuthenticatedRitmoRoute: AuthenticatedRitmoRoute,
  AuthenticatedSimuladosRoute: AuthenticatedSimuladosRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRoute,
  AuthenticatedMaterialMaterialIdRoute: AuthenticatedMaterialMaterialIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicNotifyCronRoute: ApiPublicNotifyCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
